### ISSUE TITLE
Read_Name in InputOutputUtils.pp 

### ISSUE THREAD

**Issue by CoLiTo94** [kostergroup/SIMsalabim#3]
Hello everyone,

I tried to use SimSS version 4.35 on Windows 10 today and got issues with the generation profile string Gen_profile.  In my case the procedure Read_Name of InputOutputUtils.pp imports the string Gen_profile with an additional ' at the beginning and end (e.g. '''none''' instead of 'none'). Due to this issue the boolean Use_gen_profile:= lowercase(Trim(Gen_profile))<>'none'; is always true and the file with the generation profile is not found.

**Comment by kostergroup** [comment]
Dear CoLiTo94,
many thanks for your message. 
So just to make sure I understand, you used Gen_profile = 'none', rather than Gen_profile = none? I designed this such that it works without quotes (i.e. it's not counting on quotes), but in the manual I say 'none' to make clear that you can simply put none. Probably confusing... Thanks for the suggested code, I'll copy this into a new version.

jan anton

**Comment by CoLiTo94** [comment]
Hi Jan Anton,

You are correct, I did use Gen_profile = 'none' instead of Gen_profile = none.
